version: 1.0.0
# Be careful about the indent
#theme: cutie
google-analytics: UA-xxxxxxxx-1
author_link: http://link/to/your/personal/website
cutie:
  logo: /your/path/to/logo/image
  slogan: This is a slogan.
  signature: SIGNATURE
# Configure navigation menu, provide a relative link and a path to icon (icon should better be square)
# If menu is absent, only "archive" and "search" menu items will be preserved
# Configurable menu items should not exeed 4, otherwise the last ones will be ignored
  menu:
    Resume: 
      link: /resume/
      icon: /images/resume.svg
    Projects: 
      link: /categories/projects/
      icon: /images/projects.svg
    Notes: 
      link: /categories/notes/
      icon: /images/notes.svg
    Fun: 
      link: /categories/fun/
      icon: /images/fun.svg
# As long as the name matches the font awesome icon name, you can add even more social links
# Tip: the social link can be a QRCODE link
  social:
    medium: 
    skype: 
    slack: 
    steam: 
    tumblr: 
    whatsapp: 
    youtube: 
    snapchat: 
    instagram: 
    qq: 
    google-plus: 
    twitter: 
    facebook: 
    weibo: 
    weixin: 
    github: https://your/github/profile/link
    linkedin: https://your/linkedin/profile/link
# Enable/disable instant click, if absent, it means disabled.
  instantclick: false # or you can set it to be "true" to enable